# Generated by Django 2.2.6 on 2019-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_test', '0002_auto_20191102_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='i. Keep an unique email.', max_length=255, unique=True),
        ),
    ]
