# Generated by Django 2.2.6 on 2019-11-02 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_test', '0004_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email_or_phone',
            field=models.CharField(default=django.utils.timezone.now, help_text='<br>i. Keep an unique email.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
