# Generated by Django 2.2.6 on 2019-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_test', '0005_auto_20191103_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_or_phone',
            field=models.CharField(help_text='<br>i. Keep an unique email.', max_length=255),
        ),
    ]
