# Generated by Django 2.2.6 on 2019-11-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_test', '0006_auto_20191103_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_or_phone',
            field=models.CharField(max_length=30),
        ),
    ]
