# Generated by Django 2.2.6 on 2019-11-02 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_test', '0008_auto_20191103_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_or_phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, help_text='i. Keep an unique email.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
