# Generated by Django 2.2.6 on 2019-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_test', '0009_auto_20191103_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='i. Keep an unique email.', max_length=255, unique=True),
        ),
    ]
